### ISSUE TITLE
Default Mythic Metals kubejs errors messing messing with my pack

### ISSUE THREAD

**Issue by ClaudiusMinimus** [Noaaan/MythicMetals#158] opened 2023-04-07 19:23 UTC
I am porting my pack "[Create Conquest Arcane](https://www.curseforge.com/minecraft/modpacks/create-conquest-arcane)" ("CCA") to fabric and just added Mythic Metals. On the first load on my test world, I was presented with the following errors:
![image](https://user-images.githubusercontent.com/17887664/230664525-fe85d232-0d3a-4faa-bea2-a5f56a0f6a74.png)
After inspecting the kubejs log (see attached) I discovers the cause comes from Alloy Forge recipes.

[cca_kubejs_server.txt](https://github.com/Noaaan/MythicMetals/files/11180947/cca_kubejs_server.txt) (The also contains lots of errors from Conquest Reforged, which are unrelated and I am working on addressing)
[cca_mythic_metal_latest.log](https://github.com/Noaaan/MythicMetals/files/11180948/cca_mythic_metal_latest.log)

I've used the Alloy Forge in other packs in the past and would truly love to use it now. However, these errors are interfering with working on the pack - hopefully, they will be quickly addressed so I can keep the mod!

Thank you,
CM

**Comment by Noaaan** [comment] 2023-04-07 20:57
Hiya
As you state, this issue is indeed related to Alloy Forgery, it is in fact a duplicate of https://github.com/wisp-forest/alloy-forgery/issues/98 and https://github.com/wisp-forest/alloy-forgery/issues/102.
It has been resolved in the beta release of AF for 1.19.4. 

I do want to note that as stated in the latter issue, there are no current plans to backport this to 1.19.2. For that reason I recommend using a bundled datapack for the Alloy Forge recipes. I believe KubeJS lets you handle this.

**Closed as completed by Noaaan** 2023-04-07 20:57 UTC
