### ISSUE TITLE
Conflict with Mythic Decorations? Crash on startup

### ISSUE THREAD

**Issue by Shiroo2157** [Noaaan/MythicMetals#245] opened 2024-06-12 08:27 UTC
App: Curseforge

Modloader: Fabric 0.15.11

Minecraft version: 1.20.1

Mods & versions/files: 
Mythic Metals 0.19.9
Mythic Metals Decorations 0.60.0
Alloy Forgery 2.1.2
owo (owo-lib) 0.11.2
Fabric API 0.92.2

issue: 
Seems to be a conflict between Mythic Metals and Mythic Metals Decorations, where it crashes on startup. Mythic Metals without decorations works as intended, but crashes with decorations. Using mythic metals 0.19.8 also works with decorations with no crash. 

crash log included
[myth deco.txt](https://github.com/user-attachments/files/15801049/myth.deco.txt)

**Comment by Noaaan** [comment] 2024-06-12 10:14
Duplicate of https://github.com/Noaaan/MythicMetalsDecorations/issues/22

**Closed as not planned by Noaaan** 2024-06-12 10:14 UTC
Labels: duplicate
