### ISSUE TITLE
Crash with Aether Redux seems to still happen in Mythic Metals - 0.19.5

### ISSUE THREAD

**Issue by AndreaSpaghetti** [Noaaan/MythicMetals#231] opened 2024-03-17 07:51 UTC
It seems that Aether Redux and Mythic Metals are still crashing even after the latest update.

Crash Log: [https://pastebin.com/mdT9NjG5](url)

I loaded an installation with only those two mods present to confirm the issue is solely between these two. The ticked entity seems to always be a vanilla mob but alas I don't know if it's this issue is only on my part u-u

**Comment by Noaaan** [comment] 2024-03-17 13:10
Thanks for the crashlog. I think I know where this issue happens. I will close this as a duplicate of #229 and track it there.

**Closed as completed by Noaaan** 2024-03-17 13:10 UTC
Labels: duplicate
