### ISSUE TITLE
World Gen

### ISSUE THREAD

**Issue by Polyphysim** [Noaaan/MythicMetals#100] opened 2022-08-07 02:22 UTC
Mods like terralith don't work with Mythic Metals. Creating a world with both mods leads to a crash while a world is being made. Could be the extra ores added to the game. Terralith also changes how ores generate..

**Comment by Noaaan** [comment] 2022-08-07 02:25
This is a duplicate of #85, and is already fixed for next release. It will be available soon

**Closed as completed by Noaaan** 2022-08-07 02:25 UTC
