### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by MechanosG** [Noaaan/MythicMetals#118] opened 2022-10-02 22:11 UTC
I probably did something wrong.  Did I do something wrong?

[-Crash Log-](https://mclo.gs/UkKUz5V)

**Comment by Noaaan** [comment] 2022-10-02 22:13
Duplicate of #117

**Closed as not planned by Noaaan** 2022-10-02 22:13 UTC
Labels: duplicate

**Comment by MechanosG** [comment] 2022-10-04 17:45
Recent update fixed it.  :)
