### ISSUE TITLE
using an anvil causes a crash upon putting any item in a slot

### ISSUE THREAD

**Issue by ChicagoSpud** [Noaaan/MythicMetals#253] opened 2024-07-11 09:55 UTC
minecraft 1.21
Mythicmetals-0.20+1.21-alpha4
 i was trying to apply looting 3 to a diamond sword and when i put either the book or sword into their slot the game freezes then crashes shortly after below is a crash log.
[anvil-crash-report-mythic-metals-alpha-4.txt](https://github.com/user-attachments/files/16174676/anvil-crash-report-mythic-metals-alpha-4.txt)

**Comment by Noaaan** [comment] 2024-07-11 11:19
The crash seems to stem from bclib, which is used by BetterNether and BetterEnd

**Comment by ChicagoSpud** [comment] 2024-07-11 19:29
so if i remove both mods should it work fine? i havent entered/generated either the end or nether

**Comment by Noaaan** [comment] 2024-07-12 05:52
You would likely also need to remove their dependencies. Looking at the issue tracker this is caused by bclib: https://github.com/quiqueck/BCLib/issues/181

**Comment by Noaaan** [comment] 2024-07-17 19:10
Looking more into the issue I cannot say if this is caused by Mythic Metals in any way. I will close this issue for now as I do believe this is on bclib's end

**Closed as not planned by Noaaan** 2024-07-17 19:10 UTC
Labels: bug, compatibility
