### ISSUE TITLE
Crashing randomly

### ISSUE THREAD

**Issue by Stick404** [Noaaan/MythicMetals#134] opened 2022-11-28 19:11 UTC
The mod crashes randomly, sorry if it is not mythic metals it is the most pronounced part on the crash report.
the crash report https://pastebin.com/qtWQY8FU

**Comment by Noaaan** [comment] 2022-11-28 20:18
Oh no, not this again. This is kinda a duplicate of #94, albeit with a new set of mods.
I have not been able to re-produce this, but I do catch the exception in order to track this obscure issue. 
I will close this for now and add this log to the list. If what you say is true about this happening often, then your modlist has a higher chance to finally expose the problem. Thanks for reporting!

**Closed as completed by Noaaan** 2022-11-28 20:18 UTC
Labels: bug, duplicate
