### ISSUE TITLE
Crashing after open alloy forge controller

### ISSUE THREAD

**Issue by VortriX13** [Noaaan/MythicMetals#136] opened 2022-12-07 12:26 UTC
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2022-12-07 09:16:59
Description: Rendering screen

java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
	at net.minecraft.class_437.method_25394(class_437.java:106)
	at net.minecraft.class_465.method_25394(class_465.java:104)
	at io.wispforest.owo.ui.base.BaseOwoHandledScreen.method_25394(BaseOwoHandledScreen.java:156)
	at wraith.alloyforgery.client.AlloyForgeScreen.method_25394(AlloyForgeScreen.java:39)
	at net.minecraft.class_757.method_3192(class_757.java:881)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
	at net.minecraft.class_437.method_25394(class_437.java:106)
	at net.minecraft.class_465.method_25394(class_465.java:104)
	at io.wispforest.owo.ui.base.BaseOwoHandledScreen.method_25394(BaseOwoHandledScreen.java:156)
	at wraith.alloyforgery.client.AlloyForgeScreen.method_25394(AlloyForgeScreen.java:39)

-- Screen render details --
Details:
	Screen name: wraith.alloyforgery.client.AlloyForgeScreen
	Mouse location: Scaled: (320, 180). Absolute: (960.000000, 540.000000)
	Screen size: Scaled: (640, 360). Absolute: (1920, 1080). Scale factor of 3.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:881)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['ScienceMaker'/28808, l='ClientLevel', x=-99.18, y=82.00, z=108.38]]
	Chunk stats: 1024, 441
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,71,0), Section: (at 0,7,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 9207295 game time, 9543125 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_1514(class_310.java:787)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, Supplementaries Generated Pack

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1239631536 bytes (1182 MiB) / 3271557120 bytes (3120 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 6
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3500 6-Core Processor              
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: unknown
	Frequency (GHz): 3.59
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 6
	Graphics card #0 name: NVIDIA GeForce GTX 1060 6GB
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1c06
	Graphics card #0 versionInfo: DriverVersion=31.0.15.2737
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 35230.57
	Virtual memory used (MB): 30615.27
	Swap memory total (MB): 18894.91
	Swap memory used (MB): 8236.66
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Fabric Mods: 
		additionaladditions: Additional Additions 5.1.0
			libgui: LibGui 6.0.0-beta.5+1.19-pre1
				jankson: Jankson 4.1.1+j1.2.1
				libninepatch: LibNinePatch 1.1.0
		additionalbanners: AdditionalBanners 10.1.2
		adorn: Adorn 3.7.0+1.19.2
		adventurez: AdventureZ 1.4.17
		ae2: Applied Energistics 2 12.9.1
			noindium: No Indium? 1.1.0+1.19
		alloy_forgery: Alloy Forgery 2.0.17+1.19
		appleskin: AppleSkin 2.4.1+mc1.19
		architectury: Architectury 6.3.56
		attributefix: AttributeFix 17.1.2
		badpackets: Bad Packets 0.2.1
		bcc: BetterCompatibilityChecker 2.0.2-build.16+mc1.19.1
		bclib: BCLib 2.1.4
		bedbenefits: BedBenefits 9.1.2
		betteradvancements: Better Advancements 0.2.2.142
		betteranimalsplus: Better Animals Plus 1.19-11.0.7
		betterdungeons: YUNG's Better Dungeons 1.19.2-Fabric-3.2.1
		betterend: Better End 2.1.2
		bettermineshafts: YUNG's Better Mineshafts 1.19.2-Fabric-3.2.0
		betternether: Better Nether 7.1.2
		betterstrongholds: YUNG's Better Strongholds 1.19.2-Fabric-3.2.0
		blur: Blur (Fabric) 2.6.0
			satin: Satin 1.8.0
		bookshelf: Bookshelf 16.1.11
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.4.5-1.19.2
			maelstrom_library: Maelstrom Library 1.3-1.19-pre1
			multipart_entities: MultipartEntities 1.2-1.19-pre1
		botanypots: BotanyPots 9.0.14
		botanytrees: BotanyTrees 5.0.1
		byg: Oh The Biomes You'll Go 2.0.0.13
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
		cardinal-components: Cardinal Components API 5.0.2
			cardinal-components-base: Cardinal Components API (base) 5.0.2
			cardinal-components-block: Cardinal Components API (blocks) 5.0.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.2
			cardinal-components-entity: Cardinal Components API (entities) 5.0.2
			cardinal-components-item: Cardinal Components API (items) 5.0.2
			cardinal-components-level: Cardinal Components API (world saves) 5.0.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.0.2
			cardinal-components-world: Cardinal Components API (worlds) 5.0.2
		charm: Charm 4.4.4
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		charmofundying: Charm of Undying 6.0.0+1.19.2
		cleancut: CleanCut 1.19.2-5.1-fabric
		cloth-api: Cloth API 4.0.65
			cloth-basic-math: cloth-basic-math 0.6.1
			cloth-client-events-v0: Cloth Client Events v0 4.0.65
			cloth-common-events-v1: Cloth Common Events v1 4.0.65
			cloth-scissors-api-v1: Cloth Scissors API v1 4.0.65
			cloth-utils-v1: Cloth Utils v1 4.0.65
		cloth-config: Cloth Config v8 8.2.88
		clumps: Clumps 9.0.0+11
		colouredtooltips: ColouredTooltips 18.1.3
		connectivity: Connectivity Mod 1.19-3.3
		continuity: Continuity 2.0.1+1.19
		controlling: Controlling For Fabric 10.0+7
		crafttweaker: CraftTweaker 10.0.16
			org_javassist_javassist: javassist 3.29.0-GA
			org_reflections_reflections: reflections 0.10.2
		creeperoverhaul: Creeper Overhaul 2.0.5
		croptopia: Croptopia 2.1.2
			com_typesafe_config: config 1.4.1
			io_leangen_geantyref_geantyref: geantyref 1.3.11
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		darkutils: DarkUtilities 13.1.2
		dashloader: DashLoader 4.1.3+1.19
			com_github_luben_zstd-jni: zstd-jni 1.5.2-2
			dev_quantumfusion_hyphen: Hyphen 0.2.2
			dev_quantumfusion_taski: Taski 1.1.0
		decorative_blocks: Decorative Blocks 3.0.0
		deeperdarker: Deeper and Darker 1.1.4
			customportalapi: Custom Portal Api 0.0.1-beta54-1.19
			paragon: Paragon 1.0.3
		dragonloot: DragonLoot 1.1.2
		dummmmmmy: MmmMmmMmmMmm 1.19-1.5.3
		ecologics: Ecologics 2.1.10
		elytraslot: Elytra Slot 6.0.0+1.19.2
		enchdesc: EnchantmentDescriptions 13.0.3
		entityculling: EntityCulling-Fabric 1.5.2-mc1.19
			com_logisticscraft_occlusionculling: occlusionculling 0.0.6-SNAPSHOT
		equipmentcompare: Equipment Compare 1.3.1
		expandability: ExpandAbility 7.0.0
			com_github_llamalad7_mixinextras: MixinExtras 0.1.0-rc5
		explorerscompass: Explorer's Compass 1.19.2-2.2.0-fabric
		extraalchemy: Extra Alchemy 1.9.0
		extraorigins: Extra Origins 1.19-2
		fabric-api: Fabric API 0.68.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.13+0d0f210290
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.12+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.20+0d0f210290
			fabric-block-api-v1: Fabric Block API (v1) 1.0.1+12bfe4ea90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.22+c6af733c90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.3+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.13+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.1.9+93d8cb8290
			fabric-commands-v0: Fabric Commands (v0) 0.2.30+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.38+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.4.3+6064db2a90
			fabric-convention-tags-v1: Fabric Convention Tags 1.1.3+93d8cb8290
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.7+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.2+ad31814d90
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.33+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.2+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.31+6eb9a2a190
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.31+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.23+c6af733c90
			fabric-item-api-v1: Fabric Item API (v1) 1.6.1+fa140d5990
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.35+9244241690
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.23+aaaf9d3390
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.21+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.2+9244241690
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.9+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.12+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.5+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.20+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.19+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.8+3b1d070f90
			fabric-networking-v0: Fabric Networking (v0) 0.3.25+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.1.2+06e0e25190
			fabric-particles-v1: Fabric Particles (v1) 1.0.12+79adfe0a90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.29+9244241690
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.1.0+e7aeff4590
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.17+aeb40ebe90
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.22+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.17+0d0f210290
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.9+c6af733c90
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.25+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.11.1+73145abb90
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.1+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.1+0d0f210290
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.29+0d0f210290
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.4+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.1+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.22+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.3+9d081d6490
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.2+42d99c3290
		fabric-language-kotlin: Fabric Language Kotlin 1.8.7+kotlin.1.7.22
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.22
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.22
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.5
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		fabricloader: Fabric Loader 0.14.10
		fallingtree: FallingTree 3.10.0
		farmersdelight: Farmer's Delight 1.19.2-1.3.9
		faux-custom-entity-data: Faux-Custom-Entity-Data 2.0.2
		ferritecore: FerriteCore 5.0.3
		findme: FindMe 3.1.0
		forgeconfigapiport: Forge Config API Port 4.2.7
		frame: Frame 0.26.1+1.19-fabric
			frame-api-base: Frame Base 0.2.1+906ebc04a9
			frame-blocks-v0: Frame Blocks (v0) 0.1.3+233e7428a9
			frame-config-v0: Frame Config (v0) 0.3.1+0fa45150a9
			frame-content-registries-v0: Frame Content Registries (v0) 0.4.0+2876b511a9
			frame-enchantments-v0: Frame Enchantments (v0) 0.1.0+4093105da9
			frame-game-rules-v0: Frame Game Rules (v0) 0.2.4+e7ce56a6a9
			frame-items-v0: Frame Items (v0) 0.1.3+906ebc04a9
			frame-loot-tables-v0: Frame Loot Tables (v0) 0.1.4+4f7341eca9
			frame-registries-v0: Frame Registries (v0) 0.1.1+0e0ec74ea9
			frame-rendering-v0: Frame Rendering (v0) 0.1.5+906ebc04a9
			frame-tabbed-item-groups-v0: Frame Tabbed Item Groups (v0) 0.2.4+0aca9b56a9
			frame-toymaker-v0: Frame Data Generation Helpers (v0) 0.6.1+b13741c3a9
			frame-woods-v0: Frame Woods (v0) 0.2.1+6a33fbada9
		fwaystones: Fabric Waystones 3.0.5+mc1.19.2
		geckolib3: Geckolib 3.1.37
			com_eliotlash_mclib_mclib: mclib 20
		go-fish: Go Fish 1.6.0-1.19.1
		goblintraders: Goblin Traders 1.5.2
		graveyard: The Graveyard 2.3
		guardvillagers: Guard Villagers Fabric 1.19.2-1.0.16
		harvest_scythes: Harvest Scythes 2.5.4+mc1.19.2
		iceberg: Iceberg 1.0.46
		indium: Indium 1.0.9+mc1.19.2
		ingredient-extension-api: Ingredient Extension API 3.0.6
		inmis: Inmis 2.7.1-1.19
			omega-config: OmegaConfig 1.2.3-1.18.1
		inventorysorter: Inventory Sorter 1.8.10-1.19
			kyrptconfig: Kyrpt Config 1.4.14-1.19
		iris: Iris 1.4.3
			io_github_douira_glsl-transformer: glsl-transformer 1.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.10.1
		itemfilters: Item Filters 1902.2.9-build.46
		jade: Jade 8.6.0
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 11.4.0.287
		jeresources: Just Enough Resources 1.1.1.184
		krypton: Krypton 0.2.1
			com_velocitypowered_velocity-native: velocity-native 3.1.2-SNAPSHOT
		lambdynlights: LambDynamicLights 2.1.2+1.19
			pride: Pride Lib 1.1.2+1.19
			spruceui: SpruceUI 4.0.0+1.19
		lazydfu: LazyDFU 0.1.3
		lightoverlay: Light Overlay 7.0.0
		lithium: Lithium 0.10.2
		magnumtorch: Magnum Torch 4.2.0
		mcwbridges: Macaw's Bridges 2.0.5
		mcwdoors: Macaw's Doors 1.0.7
		mcwfences: Macaw's Fences and Walls 1.0.6
		mcwlights: Macaw's Lights and Lamps 1.0.4
		mcwpaintings: Macaw's Paintings 1.0.4
		mcwroofs: Macaw's Roofs 2.2.1
		mcwtrpdoors: Macaw's Trapdoors 1.0.7
		mcwwindows: Macaw's Windows 2.1.0
		medievalorigins: Medieval Origins 1.19.x-4.1.3
		midnightlib: MidnightLib 1.0.0
		minecraft: Minecraft 1.19.2
		modmenu: Mod Menu 4.1.1
		moonlight: Moonlight 1.19.2-2.1.13
		morevillagers: More Villagers 4.0.2
		mousetweaks: Mouse Tweaks 2.22
		mythicmetals: Mythic Metals 0.16.4+1.19.2
		naturescompass: Nature's Compass 1.19.2-2.1.0-fabric
		nochatreports: No Chat Reports 1.19.2-v1.13.12
		notenoughanimations: NotEnoughAnimations 1.6.2
		onsoulfire: On Soul Fire 1.19-2
		origins: Origins 1.7.1
			apoli: Apoli 2.6.1
				additionalentityattributes: Additionalentityattributes 1.0.0+1.19
				calio: Calio 1.7.0
				playerabilitylib: Pal 1.6.0
			reach-entity-attributes: Reach Entity Attributes 2.3.0
		origins-classes: Origins: Classes 1.4.0
		owo: oωo 0.8.5+1.19
			blue_endless_jankson: jankson 1.2.1
		patchouli: Patchouli 1.19.2-77-FABRIC
			fiber: fiber 0.23.0-2
		pehkui: Pehkui 3.6.0+1.14.4-1.19.3
			kanos_config: Kanos Config 0.3.1+1.14.4-1.19
		phosphor: Phosphor 0.8.1
		pigpen: PigPen 11.1.2
		puzzleslib: Puzzles Lib 4.3.12
		reborncore: Reborn Core 5.4.0
			team_reborn_energy: Energy 2.3.0
		reeses-sodium-options: Reese's Sodium Options 1.4.9+mc1.19.2-build.67
		repurposed_structures: Repurposed Structures 6.1.2+1.19
		rhino: Rhino 1902.2.2-build.264
		rpg_origins: RPG Origins 1.2.2
		runelic: Runelic 14.1.2
		skinlayers: 3d Skin Layers 1.5.2-mc1.19.1
		smallships: Small Ships 2.0.0a1.1.1
		smoothboot: Smooth Boot 1.19-1.7.1
		sodium: Sodium 0.4.4+build.18
			org_joml_joml: joml 1.10.4
		sodium-extra: Sodium Extra 0.4.14+mc1.19.2-build.80
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		spark: spark 1.9.45
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		stoneholm: Stoneholm 1.4.4
		structory: Structory 1.0.1
		supplementaries: Supplementaries 1.19.2-2.2.24
		terrablender: TerraBlender 2.0.1.130
		thonkutil: ThonkUtil 2.15.4+1.19
			thonkutil-base: ThonkUtil Base 1.13.2+4a8c408a57
			thonkutil-capes-v1: ThonkUtil Capes (v1) 1.4.2+3eb2749857
			thonkutil-coords-v1: ThonkUtil Coords (v1) 1.1.2+8ff533c957
			thonkutil-customization-v1: ThonkUtil Customization (v1) 1.1.2+8ff533c957
			thonkutil-legacy: ThonkUtil Legacy 1.1.2+5d4263f557
			thonkutil-modchecker-v1: ThonkUtil ModChecker (v1) 1.1.3+bd4b387957
			thonkutil-potions-v0: ThonkUtil Potions (v0) 1.5.2+8ff533c957
			thonkutil-titlescreen-v1: ThonkUtil TitleScreen (v1) 1.2.2+8ff533c957
			thonkutil-trades-v1: ThonkUtil Trades (v1) 1.2.2+8ff533c957
		tipsmod: Tips 8.0.3
		tlskincape: TLSkinCape 1.27
		toolstats: ToolStats 12.0.2
		tradingpost: Trading Post 4.2.0
		trinkets: Trinkets 3.4.1
		twigs: Twigs 2.0.0-beta.9+1.19-fabric
		twilightforest: The Twilight Forest 4.2.310
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			here-be-no-dragons: Here be no Dragons! 1.0.0
			javax_annotation_javax_annotation-api: javax.annotation-api 1.3.2
			mm: Manningham Mills 2.3
			porting_lib: Porting Lib 2.0.591+1.19.2
				porting_lib_base: Porting Lib Base 2.0.591+1.19.2
				porting_lib_entity: Porting Lib Entity 2.0.591+1.19.2
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.0.591+1.19.2
				porting_lib_model_generators: Porting Lib Model Generators 2.0.591+1.19.2
				porting_lib_models: Porting Lib Models 2.0.591+1.19.2
				porting_lib_networking: Porting Lib Networking 2.0.591+1.19.2
				porting_lib_obj_loader: Porting Lib Obj Loader 2.0.591+1.19.2
					porting_lib_model_loader: Porting Lib Model Loader 2.0.591+1.19.2
				porting_lib_tags: Porting Lib Tags 2.0.591+1.19.2
				porting_lib_transfer: Porting Lib Transfer 2.0.591+1.19.2
					porting_lib_extensions: Porting Lib Extensions 2.0.591+1.19.2
						porting_lib_accessors: Porting Lib Accessors 2.0.591+1.19.2
						porting_lib_attributes: Porting Lib Attributes 2.0.591+1.19.2
							porting_lib_constants: Porting Lib Constants 2.0.591+1.19.2
						porting_lib_common: Porting Lib Common 2.0.591+1.19.2
			serialization_hooks: Serialization Hooks 0.3.22
		villagernames: Villager Names 4.0.8
		visualworkbench: Visual Workbench 4.2.0
		xaerominimap: Xaero's Minimap 22.16.3
		xaeroworldmap: Xaero's World Map 1.28.4
		yet-another-config-lib: YetAnotherConfigLib 1.7.1
		yigd: You're in Grave Danger 1.4.6
		yungsapi: YUNG's API 1.19.2-Fabric-3.8.2
		zoomify: Zoomify 2.8.0
			dev_isxander_settxi_settxi-core: settxi-core 2.10.3
			dev_isxander_settxi_settxi-gui: settxi-gui 2.10.3
			dev_isxander_settxi_settxi-kotlinx-serialization: settxi-kotlinx-serialization 2.10.3
			settxi-gui-yacl: Settxi Gui (YetAnotherConfigLib) 2.10.3
	Loaded Shaderpack: Sildur's+Vibrant+Shaders+v1.41+Medium.zip
		Profile: Custom (+1 option changed by user)
	NEC status: No NEC detected
	Launched Version: fabric-loader-0.14.10-1.19.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2 GL version 3.2.0 NVIDIA 527.37, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: Fabric Mods
	Current Language: English (US)
	CPU: 6x AMD Ryzen 5 3500 6-Core Processor

**Comment by Noaaan** [comment] 2022-12-07 12:29
Duplicate of #135

**Closed as not planned by Noaaan** 2022-12-07 12:29 UTC
Labels: duplicate
