### ISSUE TITLE
Enchant Giver cannot change Mythic effects

### ISSUE THREAD

**Issue by itsdinkd** [Noaaan/MythicMetals#60] opened 2022-01-23 19:09 UTC
![image](https://user-images.githubusercontent.com/35115304/150694072-e5126e67-bd98-4f9c-8d9a-aabfe9df251f.png)

latest version of both mods for fabric 1.18.1. it automatically converts back to mending

**Comment by Noaaan** [comment] 2022-01-26 00:36
This is intended behaviour, as I currently have set the `replace` value to `true` in my EnchantGiver config code for my items.

**Comment by itsdinkd** [comment] 2022-01-26 03:36
Any chance on making this optional? The allows players of my modpack AQM2
to easily get mending from a disenchanter mod it uses.

**Comment by Noaaan** [comment] 2022-01-26 14:01
The whole point of EnchantGiver is to *unenchanted* items to gain abilities from enchantments, not to grant items enchants on craft. This is further reinforced with the fact you can enchant any item with an ability from EnchantGiver. Being able to disenchant these would go against the whole point of this functionality.  
![image](https://user-images.githubusercontent.com/4163353/151176617-c9443a06-73c5-4e97-82e6-b5afed20ba2e.png)

**Comment by itsdinkd** [comment] 2022-01-26 18:13
I get the purpose of EnchantGiver. It's not something I added into my pack,
as it's a required dependency. Regardless of that, that's why I'd like to
change your mending enchantment to a different enchantment. The whole point
of modpacks is customization and tailoring to the needs of the pack, not
what we think something should be used for. I have to work with what I'm
given with some mods.

So any chance on making it so you do not force settings with enchant giver?

**Comment by Noaaan** [comment] 2022-01-27 02:08
From further investigation the true issue here is related to EnchantGiver. I might still change the forceful config but for now I am closing this issue.

**Closed as completed by Noaaan** 2022-01-27 02:08 UTC
