### ISSUE TITLE
Java error on MM 0.19.8

### ISSUE THREAD

**Issue by Hexblood** [Noaaan/MythicMetals#241] opened 2024-05-30 22:48 UTC
As of this writing the latest build is coming up with a Java class error. Loading via Modrinth on default Java settings.

Mythic Metals 0.19.8+1.20.1
MC 1.20.1
Fabric 0.15.11
Fabric API 0.92.2+1.20.1

Log: https://mclo.gs/qLT4Up3

**Comment by Noaaan** [comment] 2024-05-30 23:47
Can confirm. This is caused by an accidental compile against Java 21, as I was working on 1.20.6+ at the time. You can temporarily mitigate this by using a newer version of Java, although I will have a fixed release tomorrow

**Comment by Hexblood** [comment] 2024-05-31 01:18
Cool, thanks. I kinda figured it was something like that.

Is there any complications by downgrading the mod to the previous build and update to the new version tomorrow? Or is there a change that would impact the world?

**Comment by Noaaan** [comment] 2024-05-31 10:40
I would always suggest making a backup when upgrading mods. Assuming you are coming from 0.19.7: For this version of Mythic Metals you should not experience any breaking changes going to 0.19.8+

**Comment by Noaaan** [comment] 2024-06-02 16:06
Should be fixed as of 0.19.8-hotfix release

**Closed as completed by Noaaan** 2024-06-02 16:06 UTC
Labels: bug
