### ISSUE TITLE
Mythic metals mythril drill

### ISSUE THREAD

**Issue by Anderval2119** [Noaaan/MythicMetals#194] opened 2023-09-27 21:54 UTC
Hello I was using the mythril drill and I put an upgrade that gets auto repair. But there is no autorepairing yet.
How can I repair this? And there's some upgrades that i can't craft it

**Comment by Noaaan** [comment] 2023-09-28 15:10
The upgrades marked as "Rare Drops" aren't craftable since they are dropped rarely when mining certain ores. The auto repair itself isn't very noticable, since it passively repairs itself while you are holding it in your hand, and to not annoy you while doing something like mining obsidian it will not update in your hand similar to how regular pickaxes do with mending.
 If you are planning to repair it in an anvil you should be able to repair it simply by using Mythril Ingots

**Comment by DiamondkingID** [comment] 2023-09-29 16:47
i was testing the prometheum bouquet and it seemed like it was not auto repairing the drill, i was on version 0.18.2+1.20. i sat with it in my main hand for 12+ minutes and it did not gain any durability. does it need to be active to work or is it not working?

**Comment by Noaaan** [comment] 2023-09-29 16:58
Confirmed bug

**Closed as completed** 2023-09-29 17:03 UTC
Labels: bug, question

**Comment by mirza0244** [comment] 2025-06-12 11:19
how can i find durasteel

**Comment by Noaaan** [comment] 2025-06-12 19:03
Hello @mirza0244. Durasteel can be forged in a tier 2 Alloy Forge using Quadrillum and Manganese.
In the future, please don't ask questions by commenting on ancient issues. Feel free to ask them in CurseForge comment section, or by joining the [Wraith Coding Sesh Discord Server](https://discord.com/invite/69cKvQWScC). You can also find helpful answers by by reading the FAQ on the Mythic Metals Wiki: https://wiki.mythicmetals.com/faq/#how-do-i-craft-x
