### ISSUE TITLE
Kicked from server when mod is interacted with

### ISSUE THREAD

**Issue by Mewey-y** [Noaaan/MythicMetals#254] opened 2024-07-13 03:44 UTC
Load in is fine and can do everything else however when anyone interacts with the mod ie picks up an item or spawns in one they get kicked from the server. Works fine in singleplayer so no issue there.

Disconnect error is "Internal Exception: io.netty.handler.codec.DecoderException: Failed to decode packet 'serverbound/minecraft:set_creative_mode_slot'

Other mods work fine all dependencies are installed as said in Modrinth description. 

Using version 1.21 Alpha4

Apologies if this is a simple fix or something that you guys cannot recommend a fix for, thank you.

**Comment by Noaaan** [comment] 2024-07-13 07:59
Could you provide some more info surrounding how you re-created the issue? Mainly if you [providing a log](https://fabricmc.net/wiki/player:tutorials:logs), as it would be very helpful as it contains a lot of info regarding Mythic Metals, Fabric, and the dependencies you are using when the disconnect occurs

**Comment by Noaaan** [comment] 2024-07-15 18:43
I am not able to reproduce this issue. I am using latest Alloy Forgery (2.2.1), and the next alpha of Mythic Metals which fixes #252. Alloy Forgery is released, and for Mythic Metals you can test out the alpha from the Action: https://github.com/Noaaan/MythicMetals/actions/runs/9869137397/artifacts/1685165128

**Comment by Noaaan** [comment] 2024-08-08 22:51
Are you still experiencing this issue?

**Comment by Noaaan** [comment] 2024-08-18 20:26
Closing this due to lack of information. Feel free to re-open it should it still be a problem

**Closed as not planned by Noaaan** 2024-08-18 20:26 UTC
