### ISSUE TITLE
Weird crash with a NullPointerException on a "null attacker"

### ISSUE THREAD

**Issue by nixord** [Noaaan/MythicMetals#147] opened 2023-02-05 05:37 UTC
Heres the whole console log with the crash log as well: https://paste.ee/p/9W7ry
Im in the nether and apparently somewhere a mob or something has a Carmot Staff and its making that error.
Now I cant even enter the world cause the mob is still trying to attack me (Im assuming its a random zpiglin)

**Comment by Noaaan** [comment] 2023-02-05 09:58
Duplicate of #142. Update to the latest official release of 0.17.0

**Closed as not planned by Noaaan** 2023-02-05 09:58 UTC
Labels: duplicate

**Comment by nixord** [comment] 2023-02-05 15:14
Oh... Sorry, I didnt see it. Thank you very much <3
