### ISSUE TITLE
Crashes on server.

### ISSUE THREAD

**Issue by K0-RR** [Noaaan/MythicMetals#28] opened 2021-01-31 13:58 UTC
mc 1.16.5
fapi 0.30.0
floader 0.11.1
v. 0.9.9-snapshot-D

```
Exception in thread "main" [14:57:25] [main/INFO]: [STDERR]: java.lang.RuntimeException: Failed to setup Fabric server environment!
[14:57:25] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:52)
[14:57:25] [main/INFO]: [STDERR]: Caused by: java.lang.RuntimeException: java.lang.RuntimeException: An exception occurred when launching the server!
[14:57:25] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:108)
[14:57:25] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:50)
[14:57:25] [main/INFO]: [STDERR]: Caused by: java.lang.RuntimeException: An exception occurred when launching the server!
[14:57:25] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:64)
[14:57:25] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:106)
[14:57:25] [main/INFO]: [STDERR]: 	... 1 more
[14:57:25] [main/INFO]: [STDERR]: Caused by: java.lang.reflect.InvocationTargetException
[14:57:25] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:57:25] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[14:57:25] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:57:25] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[14:57:25] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:62)
[14:57:25] [main/INFO]: [STDERR]: 	... 2 more
[14:57:25] [main/INFO]: [STDERR]: Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[14:57:25] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:228)
[14:57:25] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
[14:57:25] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:27)
[14:57:25] [main/INFO]: [STDERR]: 	... 7 more
[14:57:25] [main/INFO]: [STDERR]: Caused by: java.lang.reflect.InvocationTargetException
[14:57:25] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:57:25] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[14:57:25] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:57:25] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[14:57:25] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
[14:57:25] [main/INFO]: [STDERR]: 	... 9 more
[14:57:25] [main/INFO]: [STDERR]: Caused by: java.lang.NoSuchMethodError: net.minecraft.class_2378.method_10250(Lnet/minecraft/class_2960;)Z
[14:57:25] [main/INFO]: [STDERR]: 	at net.fabricmc.fabric.api.biome.v1.BiomeSelectors.lambda$builtIn$1(BiomeSelectors.java:58)
[14:57:25] [main/INFO]: [STDERR]: 	at net.fabricmc.fabric.impl.biome.modification.BiomeModificationImpl.modifyBiomes(BiomeModificationImpl.java:147)
[14:57:25] [main/INFO]: [STDERR]: 	at net.minecraft.class_5382.handler$bel000$afterCreation(class_5382.java:554)
[14:57:25] [main/INFO]: [STDERR]: 	at net.minecraft.class_5382.method_29753(class_5382.java:51)
[14:57:25] [main/INFO]: [STDERR]: 	at net.minecraft.server.Main.redirect$bao000$ofRegistryOps(Main.java:1551)
[14:57:25] [main/INFO]: [STDERR]: 	at net.minecraft.server.Main.main(Main.java:146)
[14:57:25] [main/INFO]: [STDERR]: 	... 14 more
```

**Comment by Noaaan** [comment] 2021-01-31 16:32
This is a duplicate of #24. Please use 0.9.8 until the next version is released.

**Closed as completed by Noaaan** 2021-01-31 16:32 UTC
Labels: bug, duplicate
