### ISSUE TITLE
 when using shears on some leaves

### ISSUE THREAD

**Issue by aldohe** [Noaaan/MythicMetals#97] opened 2022-08-04 00:14 UTC
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 8/3/22, 6:05 PM
Description: Ticking entity

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1792.method_40131()" because the return value of "net.minecraft.class_1799.method_7909()" is null
	at net.minecraft.class_1309.mythicmetals$addArmorEffects(class_1309.java:40686)
	at net.minecraft.class_1309.handler$fmc000$mythicmetals$tick(class_1309.java:40681)
	at net.minecraft.class_1309.method_5773(class_1309.java)
	at net.minecraft.class_1308.method_5773(class_1308.java:353)
	at net.minecraft.class_638.method_18646(class_638.java:267)
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_638.method_32124(class_638.java:250)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:246)
	at net.minecraft.class_310.method_1574(class_310.java:1813)
	at net.minecraft.class_310.method_1523(class_310.java:1101)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_1309.mythicmetals$addArmorEffects(class_1309.java:40686)
	at net.minecraft.class_1309.handler$fmc000$mythicmetals$tick(class_1309.java:40681)
	at net.minecraft.class_1309.method_5773(class_1309.java)
	at net.minecraft.class_1308.method_5773(class_1308.java:353)
	at net.minecraft.class_638.method_18646(class_638.java:267)
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_638.method_32124(class_638.java:250)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:246)

-- Entity being ticked --
Details:
	Entity Type: minecraft:chicken (net.minecraft.class_1428)
	Entity ID: 382
	Entity Name: Chicken
	Entity's Exact location: 409.16, 88.00, 97.49
	Entity's Block location: World: (409,88,97), Section: (at 9,8,1 in 25,5,6; chunk contains blocks 400,-64,96 to 415,319,111), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_638.method_32124(class_638.java:250)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:246)
	at net.minecraft.class_310.method_1574(class_310.java:1813)
	at net.minecraft.class_310.method_1523(class_310.java:1101)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['aldohe'/274, l='ClientLevel', x=392.60, y=93.00, z=41.62]]
	Chunk stats: 1024, 417
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,111,0), Section: (at 0,15,0 in 0,6,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 1759856 game time, 1741201 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2288)
	at net.minecraft.class_310.method_1514(class_310.java:753)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, __MoreMcmeta Internal__

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1804260088 bytes (1720 MiB) / 4764729344 bytes (4544 MiB) up to 5234491392 bytes (4992 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz
	Identifier: Intel64 Family 6 Model 58 Stepping 9
	Microarchitecture: unknown
	Frequency (GHz): 3.39
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: NVIDIA GeForce GT 1030
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x1d01
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7212
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 1.33
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MB): 2048.00
	Memory slot #1 clockSpeed (GHz): 1.33
	Memory slot #1 type: Unknown
	Virtual memory max (MB): 28103.17
	Virtual memory used (MB): 8021.29
	Swap memory total (MB): 21998.14
	Swap memory used (MB): 1135.10
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4984M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		additionalstructures: Additional Structures 4.0.0
		adorn: Adorn 3.6.1+1.19
		advdebug: Advancements Debug 2.3.0
		adventurez: AdventureZ 1.4.14
		alloy_forgery: Alloy Forgery 2.0.15+1.19
		arcanus: Arcanus 1.30
		architects_palette: Architect's Palette Fabric 2.1.1
		architectury: Architectury 5.10.33
		attributefix: AttributeFix 15.1.3
		autoconfig1u: Auto Config v1 Updated 3.4.0
		backslot: BackSlot 1.2.8
			amecsapi: Amecs API 1.3.6+mc22w17a
		backslotaddon: BackSlot Addon 1.0.9
		badpackets: Bad Packets 0.1.2
		bcc: BetterCompatibilityChecker fabric-2.0.1-build.15
		bclib: BCLib 2.0.19
		besmirchment: Besmirchment 1.19-2
			playerabilitylib: Pal 1.6.0
			reach-entity-attributes: Reach Entity Attributes 2.3.0
			terraform-wood-api-v1: Terraform Wood API (v1) 4.1.0
		betterend: Better End 2.0.11
		betternether: Better Nether 7.0.8
		bewitchment: Bewitchment 1.19-4
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
			impersonate: Impersonate 2.6.1
			step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		bookshelf: Bookshelf 14.2.10
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.4.1-1.19
			maelstrom_library: Maelstrom Library 1.3-1.19-pre1
			multipart_entities: MultipartEntities 1.2-1.19-pre1
		bwplus: Bewitchment Plus 1.19-4
		cardinal-components: Cardinal Components API 5.0.1
			cardinal-components-base: Cardinal Components API (base) 5.0.1
			cardinal-components-block: Cardinal Components API (blocks) 5.0.1
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.1
			cardinal-components-entity: Cardinal Components API (entities) 5.0.1
			cardinal-components-item: Cardinal Components API (items) 5.0.1
			cardinal-components-level: Cardinal Components API (world saves) 5.0.1
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.0.1
			cardinal-components-world: Cardinal Components API (worlds) 5.0.1
		carrier: Carrier 1.11.0
			advanced_runtime_resource_pack: Runtime Resource Pack 0.5.5
		charm: Charm 4.1.2
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		charmofundying: Charm of Undying 6.0.0-beta.3+1.19.1
		cloth-api: Cloth API 4.0.65
			cloth-basic-math: cloth-basic-math 0.6.1
			cloth-client-events-v0: Cloth Client Events v0 4.0.65
			cloth-common-events-v1: Cloth Common Events v1 4.0.65
			cloth-scissors-api-v1: Cloth Scissors API v1 4.0.65
			cloth-utils-v1: Cloth Utils v1 4.0.65
		clumps: Clumps 9.0.0+7
		collective-fabric: Collective (Fabric) 4.27
			fiber: fiber 0.23.0-2
		conjuring: Conjuring 1.0.24+1.19
		cosmetic-armor: Cosmetic Armor 1.4.0
		crawl: Crawl 0.11.0
			mm: Manningham Mills 2.3
		ctov: ChoiceTheorem's Overhauled Villages 3.0.1
		dataattributes: Data Attributes 1.2.1
		dawn: Dawn API 3.5.0
		debugify: Debugify 2.3.2
			com_github_llamalad7_mixinextras: mixinextras 0.0.11
		deepslatecutting: Deepslate Cutting 1.4.0
		dehydration: Dehydration 1.2.9
		dragonloot: DragonLoot 1.1.1
		dummmmmmy: MmmMmmMmmMmm 1.19-1.5.3
		dungeons_arise: When Dungeons Arise 2.1.51
		dustrial_decor: Dustrial Decor 0.5
		earthbounds: Earthbounds 1.19-1.1.4
		easymagic: Easy Magic 4.0.0
		ecologics: Ecologics 2.1.5
			cloth-config: Cloth Config v6 7.0.73
		edenring: EdenRing 0.6.3
		eldritch_mobs: EldritchMobs 1.12.4
		endrem: End Remastered 5.1.1
		enhancedcelestials: Enhanced Celestials 2.1.0.0
		environmentz: EnvironmentZ 1.2.3
		expandeddelight: Expanded Delight 0.2.1
		fabric: Fabric API 0.58.0+1.19
			fabric-api-base: Fabric API Base 0.4.9+e62f51a3a9
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.7+9ff28f40a9
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.14+b2a4a624a9
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.18+9ff28f40a9
			fabric-command-api-v1: Fabric Command API (v1) 1.2.6+f71b366fa9
			fabric-command-api-v2: Fabric Command API (v2) 2.1.2+0d55f585a9
			fabric-commands-v0: Fabric Commands (v0) 0.2.23+df3654b3a9
			fabric-containers-v0: Fabric Containers (v0) 0.1.28+df3654b3a9
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.1+07df213ea9
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.8+37622d24a9
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.3+bd0a0d4aa9
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.2+a680b9b4a9
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.28+a6d2f785a9
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.16+9ff28f40a9
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.26+9ff28f40a9
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.26+df3654b3a9
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.19+18990361a9
			fabric-item-api-v1: Fabric Item API (v1) 1.5.5+35a03c43a9
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.26+9ff28f40a9
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.18+9ff28f40a9
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.16+df3654b3a9
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+33fbc738a9
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.1+03a4e568a9
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.4+9e7660c6a9
			fabric-message-api-v1: Fabric Message API (v1) 1.0.1+513f4a59a9
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.11+33fbc738a9
			fabric-models-v0: Fabric Models (v0) 0.3.15+9ff28f40a9
			fabric-networking-api-v1: Fabric Networking API (v1) 1.1.0+442de8b8a9
			fabric-networking-v0: Fabric Networking (v0) 0.3.15+df3654b3a9
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.8+9ff28f40a9
			fabric-particles-v1: Fabric Particles (v1) 1.0.8+dc39553aa9
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.18+23c4cfefa9
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.8+9ff28f40a9
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.10+5187d39fa9
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.18+df3654b3a9
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.12+9ff28f40a9
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.5+9ff28f40a9
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.20+df3654b3a9
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.14+9ff28f40a9
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.9+e62f51a3a9
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.6+5f1a85e0a9
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.24+f05effafa9
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.7+9ff28f40a9
			fabric-textures-v0: Fabric Textures (v0) 1.0.18+9ff28f40a9
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.9+e62f51a3a9
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.1+9e7660c6a9
		fabric-language-kotlin: Fabric Language Kotlin 1.8.2+kotlin.1.7.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.2
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.3
		fabricloader: Fabric Loader 0.14.8
		fallingtree: FallingTree 3.7.4
		farmersdelight: Farmer's Delight 1.19-0.3.0
		farmersknives: Farmer's Knives 2.0
		ferritecore: FerriteCore 4.2.1
		forgeconfigapiport: Forge Config API Port 4.0.2
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		frame: Frame 0.26.0+1.19
			frame-api-base: Frame Base 0.2.1+906ebc04a9
			frame-blocks-v0: Frame Blocks (v0) 0.1.3+233e7428a9
			frame-config-v0: Frame Config (v0) 0.3.1+0fa45150a9
			frame-content-registries-v0: Frame Content Registries (v0) 0.4.0+2876b511a9
			frame-enchantments-v0: Frame Enchantments (v0) 0.1.0+4093105da9
			frame-game-rules-v0: Frame Game Rules (v0) 0.2.4+e7ce56a6a9
			frame-items-v0: Frame Items (v0) 0.1.3+906ebc04a9
			frame-loot-tables-v0: Frame Loot Tables (v0) 0.1.4+4f7341eca9
			frame-registries-v0: Frame Registries (v0) 0.1.1+0e0ec74ea9
			frame-rendering-v0: Frame Rendering (v0) 0.1.5+906ebc04a9
			frame-tabbed-item-groups-v0: Frame Tabbed Item Groups (v0) 0.2.4+0aca9b56a9
			frame-toymaker-v0: Frame Data Generation Helpers (v0) 0.6.1+b13741c3a9
			frame-woods-v0: Frame Woods (v0) 0.2.1+6a33fbada9
		friendsandfoes: Friends&Foes 1.5.5
		fwaystones: Fabric Waystones 3.0.2+mc1.19
		geckolib3: Geckolib 3.1.6
			com_eliotlash_mclib_mclib: mclib 18
			com_eliotlash_molang_molang: molang 18
		geodes: More Geodes 1.4.4
		gobber2: Gobber2 2.6.23
			pugh_lib: Pugh Lib 1.4.10
			pugh_tools: Pugh Tools 1.3.13
		graveyard: The Graveyard 1.10
			omega-config: OmegaConfig 1.2.2-1.18.1
		guardvillagers: Guard Villagers Fabric 1.19-1.0.16
		icarus: Icarus 1.13
		iceberg: Iceberg 1.0.38
		immersive_weathering: Immersive Weathering 1.0.1-1.19_SNAPSHOT
		imst: Immersive structures 2.0.2
		infusion_table: Infusion Table 1.1.0
		interactic: Interactic 0.1.10+1.19
		iris: Iris 1.2.6
			org_anarres_jcpp: jcpp 1.4.14
		itemmodelfix: Item Model Fix 1.0.3+1.19
		jamlib: JamLib 0.4.1
		java: OpenJDK 64-Bit Server VM 17
		kiwi: Kiwi Lib 7.2.1
		krypton: Krypton 0.2.0
			com_velocitypowered_velocity-native: velocity-native 3.1.2-SNAPSHOT
		lambdynlights: LambDynamicLights 2.1.2+1.19
			pride: Pride Lib 1.1.2+1.19
			spruceui: SpruceUI 4.0.0+1.19
		lithium: Lithium 0.8.1
		magnumtorch: Magnum Torch 4.0.1
		mcda: MC Dungeons Armors 2.1.1
		mcdw: MC Dungeons Weapons 4.4.0-1.19
			enchant_giver: Enchant Giver 1.3.0
		mcwbridges: Macaw's Bridges 2.0.3
		medievalorigins: Medieval Origins 1.19.x-4.1.2
		medievalweapons: Medieval Weapons 1.2.1
		memoryleakfix: memory Leak Fix 1.19-0.7.0
		midnightlib: MidnightLib 0.5.2
		minecraft: Minecraft 1.19
		moborigins: Mob Origins 1.9.0
		modmenu: Mod Menu 4.0.4
		more_babies: More Babies 0.5.3
		moremcmeta: MoreMcmeta 1.19-3.0.5
		mythicmetals: Mythic Metals 0.15.1
			magna: Magna 1.8.0-1.19
		mythicmounts: Mythic Mounts 1.19-7.0
		naturalist: Naturalist 2.0.1
		naturescompass: Nature's Compass 1.19-2.0.4-fabric
		nears: Nears 1.2.3
		nochatreports: No Chat Reports 1.19-v1.2.3
		onsoulfire: On Soul Fire 1.19-2
		openloader: OpenLoader 13.1.2
		origins: Origins 1.6.2
			apoli: Apoli 2.5.1
				additionalentityattributes: Additionalentityattributes 1.0.0+1.19
				calio: Calio 1.7.0
		owo: oωo 0.7.3+1.19
		oxidized: Oxidized 1.7.1
		patchouli: Patchouli 1.19-74-FABRIC
		pehkui: Pehkui 3.3.3+1.14.4-1.19.1
			kanos_config: Kanos Config 0.3.1+1.14.4-1.19
		playerex: PlayerEx 3.3.1
			net_objecthunter_exp4j: exp4j 0.4.8
			opc: Offline Player Cache 0.6.0
			placeholder-api: Placeholder API 2.0.0-beta.7+1.19
		prefab: Prefab 4.0.0
		probablychests: Probably Chests 0.5.3-1.19
		professions: Professions 0.2.2
			com_typesafe_config: config 1.4.1
			io_leangen_geantyref_geantyref: geantyref 1.3.11
			octo-economy-api: Octo Economy API 1.0.1
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		puzzleslib: Puzzles Lib 4.0.18
		quartzelv: Quartz Elevator 2.1.3+1.19
		rare-ice: Rare Ice 0.5.0
		reeses-sodium-options: Reese's Sodium Options 1.4.4+mc1.19-build.47
		repurposed_structures: Repurposed Structures 6.1.1+1.19
		rightclickharvest: Right Click Harvest 2.2.1
		rotten: FleshZ 1.4.7
		roughlyenoughitems: Roughly Enough Items 9.1.520
		roughlyenoughprofessions: Roughly Enough Professions 1.1.1
		roughlyenoughresources: Roughly Enough Resources 2.6.0
		rpgdifficulty: Rpg Difficulty 1.2.0
		seasons: Fabric Seasons 1.4-BETA+1.19
		skyvillages: Sky Villages 1.0.2.1
		sodium: Sodium 0.4.2+build.16
			org_joml_joml: joml 1.10.4
		sodium-extra: Sodium Extra 0.4.6+mc1.19-build.47
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		spark: spark 1.9.26
		starlight: Starlight 1.1.1+fabric.ae22326
		starterkit-fabric: Starter Kit (Fabric) 3.3
		steves_vanilla: Steves Vanilla 1.0.0+1.19
		stoneholm: Stoneholm 1.4.4
		strawgolem: Straw Golem 2.0.0b1
		structory: Structory 1.0.1
		t_and_t: Towns and Towers - Structure Add-on 1.8
		things: Things 0.2.19+1.19
		thonkutil: ThonkUtil 2.15.4+1.19
			thonkutil-base: ThonkUtil Base 1.13.2+4a8c408a57
			thonkutil-capes-v1: ThonkUtil Capes (v1) 1.4.2+3eb2749857
			thonkutil-coords-v1: ThonkUtil Coords (v1) 1.1.2+8ff533c957
			thonkutil-customization-v1: ThonkUtil Customization (v1) 1.1.2+8ff533c957
			thonkutil-legacy: ThonkUtil Legacy 1.1.2+5d4263f557
			thonkutil-modchecker-v1: ThonkUtil ModChecker (v1) 1.1.3+bd4b387957
			thonkutil-potions-v0: ThonkUtil Potions (v0) 1.5.2+8ff533c957
			thonkutil-titlescreen-v1: ThonkUtil TitleScreen (v1) 1.2.2+8ff533c957
			thonkutil-trades-v1: ThonkUtil Trades (v1) 1.2.2+8ff533c957
		tlskincape: TLSkinCape 1.27
		toms_storage: Tom's Simple Storage Mod 1.3.5
		tooltiprareness: Tooltip Rareness 1.0.6
		torchbowmod: TorchBowMod 1.0
		totw_additions: Towers of the Wild: Additions 1.2.3
		tradingpost: Trading Post 4.0.0
		transparent: Transparent 5.1.0
		travelersbackpack: Traveler's Backpack 1.19-8.0.2
		trinkets: Trinkets 3.4.0
		twigs: Twigs 2.0.0-beta.8+1.19
		villagernames: Villager Names 4.0.5
		visualworkbench: Visual Workbench 4.0.0
		voidtotem: Void Totem 2.0.0
		voidz: VoidZ 1.0.8
		wandering_collector: Wandering Collector 1.1.3+mc1.19
			coat: Coat 1.0.0-beta.18+mc22w17a
			tweed4_annotated: tweed4_annotated 1.3.1+mc22w17a
			tweed4_base: tweed4_base 1.6.0+mc22w17a
			tweed4_data: tweed4_data 1.2.1+mc22w17a
			tweed4_data_hjson: tweed4_data_hjson 1.1.1+mc22w17a
			tweed4_tailor_coat: tweed4_tailor_coat 1.1.3+mc22w17a
			tweed4_tailor_screen: tweed4_tailor_screen 1.1.1+mc22w17a
		wardentools: Warden Tools 1.0
		wolveswitharmor: Wolves With Armor 1.8.0-1.19
			maybe-data: Maybe data 1.3.2-1.19-rc2
			static-content: Static Content 1.0.1-1.16.2
				staticdata: Static Data 1.1.2
		wthit: wthit 5.7.0
		xaerominimap: Xaero's Minimap 22.12.0
		xaeroworldmap: Xaero's World Map 1.26.1
		xps: Xp Obelisk 0.4.1.r_for_1.19.x_Fabric
		yigd: You're in Grave Danger 1.4.1
	Loaded Shaderpack: (off)
	Launched Version: Fabric 1.19
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce GT 1030/PCIe/SSE2 GL version 3.2.0 NVIDIA 472.12, NVIDIA Corporation
	Window size: 1360x768
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, Fabric Mods
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['aldohe'/274, l='ServerLevel[New World]', x=392.60, y=93.00, z=41.62]]
	Data Packs: vanilla, Fabric Mods, professions/fabric/normal, minecraft/fleshz_compat
	World Generation: Experimental

**Comment by Noaaan** [comment] 2022-08-04 06:00
This is a duplicate of #94 
I am still investigating the cause of this issue

**Closed as not planned by Noaaan** 2022-08-04 06:00 UTC
Labels: duplicate
