### ISSUE TITLE
[Bug] Trying to enter my SP World with Mythic Metals installed causes a server disconnect error

### ISSUE THREAD

**Issue by Gamemassa** [Noaaan/MythicMetals#256] opened 2024-07-18 21:53 UTC
Minecraft 1.21
Fabric Loader 0.16.0
Fabric API 0.100.7
Mythic Metals 0.20.0-alpha4

Ok, suuuuuper confused about this one. Now that the Alloy Forgery issue is fixed, I tried adding Mythic Metals to my modpack, and for some reason when I try to enter my _**Singleplayer World**_, I get a Network Protocol Error and get dumped back to the _**Multiplayer Server Selection Screen**_.

Crash Report (?):
https://mclo.gs/iIuagb8

**Comment by Noaaan** [comment] 2024-07-18 21:58
Duplicate of #252. Update to 0.20.0-alpha5

**Closed as not planned by Noaaan** 2024-07-18 21:58 UTC
Labels: duplicate
