### ISSUE TITLE
It is not possible to add levelz level requirements to some swords

### ISSUE THREAD

**Issue by MrOz59** [Noaaan/MythicMetals#214] opened 2023-12-04 22:51 UTC
![image](https://github.com/Noaaan/MythicMetals/assets/74338254/7a57a965-bcf0-4e71-97aa-5c0ea82212b7)
![image](https://github.com/Noaaan/MythicMetals/assets/74338254/9c1c8646-c6e7-4a7a-aa06-986a1aac5567)

I tried with custom item and it didn't work
![image](https://github.com/Noaaan/MythicMetals/assets/74338254/e2ae5e50-5331-4239-803d-1b62cd42cc9a)

I also tried with tags, it doesn't work either
![image](https://github.com/Noaaan/MythicMetals/assets/74338254/d2efbf2d-98b3-450f-8241-c0ad5b77a8af)

Swords list:

durasteel
hallowed
mythril
orichalcum
osmium
palladium
prometheum
quadrillum
runite
star platinum
steel
legendary

versions: mythicmetals-0.18.2+1.20
               levelz-1.4.11

**Comment by Noaaan** [comment] 2023-12-04 23:18
I think you might just be creating the datapack wrong. I just managed to create this myself using the following data from the [example datapack on GitHub](https://github.com/Globox1997/LevelZ/tree/1.20/exampleDatapack/data/levelz)
![image](https://github.com/Noaaan/MythicMetals/assets/4163353/31de1ca9-5a59-4be5-9e29-9181c2a5b090)

I think what you are doing wrong is in the first image provided you added a `required` field, which I do not believe is valid. In the second example it might be true it does not work because of tags, although I am unsure what the documentation exactly means with this. It is not clear whether you need to specify a tool/armor material, the type of item, and also add said item to a specific tag? (Maybe `c`?)

I recommend having [logs open](https://minecrafthopper.net/help/guides/getting-minecraft-game-output-log/) while developing datapacks. They usually throw error messages if the JSON parsing specifically is invalid. Anyhow, I can confirm this data structure with custom item works, with the side-effect of not disabling the right-click ability of Legendary Banglum Tools (I assume it does not check for using tools on blocks vs. using an item for the skill check, I advice opening a separate issue for this).
```json
{
    "replace": false,
    "skill": "strength",
    "level": 14,
    "item": "minecraft:custom_item",
    "object": "mythicmetals:durasteel_sword"
}

```

**Comment by MrOz59** [comment] 2023-12-04 23:56
![image](https://github.com/Noaaan/MythicMetals/assets/74338254/d5ae5557-b8d1-4cf2-bb1f-ec41b4258784)
![image](https://github.com/Noaaan/MythicMetals/assets/74338254/46570529-ce37-4d73-baea-740cc6ffe28c)

This is my first datapack, I don't really know what to do, the required in the first image was just an attempt that I took from one of the compatible items already present, copy your code and it still doesn't work

![image](https://github.com/Noaaan/MythicMetals/assets/74338254/870a5831-dde5-4a07-87c2-6b63bf3eb86d)
![image](https://github.com/Noaaan/MythicMetals/assets/74338254/7af28140-79d1-44be-b321-3f88d70d5cff)


If you can help me figure out if there's something I'm doing wrong, I'd appreciate it.

**Comment by Noaaan** [comment] 2024-06-11 11:23
Are you still experiencing this problem? I don't think this is an innate issue with Mythc Metals itself, but this is more likely an issue you are facing while creating your datapack. 
For now I will close this issue. If you still need support surrounding it, I suggest joining our [Discord Server](https://discord.gg/69cKvQWScC), as it is much easier/faster to help you this way.

**Closed as completed by Noaaan** 2024-06-11 11:23 UTC
Labels: compatibility, question
