### ISSUE TITLE
Recipe book not loading

### ISSUE THREAD

**Issue by hoekzemaar** [Noaaan/MythicMetals#161] opened 2023-04-12 19:23 UTC
Using version 0.17.5 on Fabric 1.19.4.

Recipe book is not loading at all. Have tried with EMI, JEI and REI. None will load recipes and don’t show up in crafting table either. Removing Mythic Metals immediately solves the problem on restart. 

Have tried via Curseforge & AT Launcher. Fresh install, new world and saved world.

**Comment by Noaaan** [comment] 2023-04-12 19:26
I am going to need a list of your mods with your log, since this does not happen with Mythic Metals alone. Sounds like a compatibility issue.

**Comment by hoekzemaar** [comment] 2023-04-13 05:13
[latest.log](https://github.com/Noaaan/MythicMetals/files/11218351/latest.log)

I have tried removing almost all other mods one by one and the issue remains for me.

**Comment by hoekzemaar** [comment] 2023-04-14 05:18
For your info. Manually removing the recipes from this folder solved the issue with regards to the recipe book not loading: \mythicmetals-0.17.5+1.19.4.jar\data\mythicmetals\recipes\mythril_drill\

**Comment by Noaaan** [comment] 2023-04-15 22:08
Confirmed the issue. It is indeed the Mythril Drill recipes breaking due to the Smithing Table recipe handlers breaking. I fixed this for the Midas Gold Sword recipes, but not the Drill. Sorry for not noticing it sooner, I will look at deploying a fix soon

**Comment by Noaaan** [comment] 2023-04-15 22:40
If you get the chance, could you try out the artifact produced by this commit? Your issue should be fixed, and as a result it should no longer crash: https://github.com/Noaaan/MythicMetals/actions/runs/4710112868

I can have this released tomorrow if it solves the issue.

**Comment by hoekzemaar** [comment] 2023-04-16 05:31
That has solved it for me thanks

**Comment by Noaaan** [comment] 2023-04-17 01:10
Fixed as of 0.17.6. Thanks you for testing and reporting!

**Closed as completed by Noaaan** 2023-04-17 01:10 UTC
Labels: bug
