### ISSUE TITLE
Game crashes upon accessing the Alloy Forge

### ISSUE THREAD

**Issue by Foxren** [Noaaan/MythicMetals#139] opened 2023-01-06 20:55 UTC
Game Version: 1.19.2
Mod Version: 0.16.4
Log: https://pastebin.com/F21GPxLc
Mod List: https://ctrlv.link/STOx

**Comment by Noaaan** [comment] 2023-01-06 21:17
Duplicate of #135

**Closed as not planned by Noaaan** 2023-01-06 21:17 UTC
Labels: duplicate
