### ISSUE TITLE
Mythic Metals Mod paired with BetterNether Mod causes the inability to access the Nether

### ISSUE THREAD

**Issue by NFSNate** [Noaaan/MythicMetals#251] opened 2024-07-07 21:11 UTC
On version 1.21 using version 0.20.0-alpha3 of mythic metals paired with Betternether (all versions for 1.21) causes the inability to access the nether

Reproduction of Error
1: Download Mythic Metals:https://modrinth.com/mod/mythicmetals/version/0.20.0+1.21-alpha3
2: Download any version of Better Nether and all the needed extensions
3: Create World
4: Attempt to go to the Nether
5: You can't

**Comment by Noaaan** [comment] 2024-07-09 06:59
Could you provide a log or a crash report of this? Asking since this could be caused by #250

**Comment by Noaaan** [comment] 2024-07-09 14:57
Testing in development this seems to be partially solved by c4d3fc4. I did run into a feature order cycle whenever I tried entering The Nether though, but I do not think that is caused by Mythic Metals. I will test further.
I suggest opening up an issue to them linking back to this, as Better Nether is also currently considered to be in alpha (unstable).

This log contains the error I faced after being able to join the world:
[latest.log](https://github.com/user-attachments/files/16145057/latest.log)

**Comment by Ollie434** [comment] 2024-07-10 08:19
I'm also encountering this issue, when on a server BetterNether paired with mythic metals was causing crashing when exploring the nether however in single player I am unable to even enter the nether for the first time after creating a world. It doesn't produce a crash in single player just simply has you sit in portal indefinitely, I will post to them as well and see if I can produce a log.

**Comment by muon-rw** [comment] 2024-07-18 01:19
Looks to have been fixed with `bclib-21.0.8`

**Comment by Noaaan** [comment] 2024-07-28 16:50
Can confirm this is fixed

**Closed as completed by Noaaan** 2024-07-28 16:50 UTC
Labels: bug, compatibility
