### ISSUE TITLE
crash after being in world a while

### ISSUE THREAD

**Issue by Monster-Zer0** [Noaaan/MythicMetals#94] opened 2022-07-28 22:31 UTC
https://aofpaste.com/nogobupuge.yaml

unfortunately I have no additional information. mythic metals is first listed in crash report, so I am hoping you can shed some light on this error.

**Comment by KavisKryptic** [comment] 2022-08-09 07:30
I wanted to bump this since I'm also encountering this issue. Here is my log: https://aofpaste.com/fowicayijo.yaml

**Comment by Noaaan** [comment] 2022-08-09 16:30
@KavisKryptic i just pushed a fix, which you can test by downloading the jar provided by [GitHub Actions](https://github.com/Noaaan/MythicMetals/actions/runs/2825952621)
Please let me know if any of you encounter this crash again

**Comment by Noaaan** [comment] 2022-08-10 17:44
https://aofpaste.com/ibafitakup.yaml

**Comment by Noaaan** [comment] 2022-08-14 21:24
As of https://aofpaste.com/uyijojipeb.yaml we now know this issue is *not* caused directly by Mythic Metals. 
There is something more to this tag checking that is failing, but we do not know what the true cause is, especially as re-producing it is really hard/random.

**Comment by KavisKryptic** [comment] 2022-08-14 22:25
Yeah, I have tried attempting reproducing the issues multiple times. But it just decides to crash randomly when I'm testing my modpack. 

I have noticed it happens when I have been using items from Mythic Metals (specifically armors & weapons, but that's probably just coincidence, not necessarily exclusive to those item types) or like putting them in my inventory. But I feel like that's obvious. 

If there's anything I can do to help, let me know. Granted, I can't imagine there's much **_I_** can do to help.

**Comment by Noaaan** [comment] 2022-08-15 19:31
Been issue hunting today. This is apparently not the newest issue around:
https://github.com/VazkiiMods/Botania/issues/4027

**Comment by Noaaan** [comment] 2022-08-18 07:11
New log. This one is interesting since in contrast to the other environments there way less mods loaded: https://pastebin.com/ANjq376s

**Comment by Monster-Zer0** [comment] 2022-08-24 21:27
https://aofpaste.com/momoconuco.yaml

**Comment by Lynxanor** [comment] 2022-09-06 17:47
https://aofpaste.com/wihevuvoxo.yaml

**Comment by AndreAugustoDev** [comment] 2022-10-01 18:42
I also have this error using 0.15.4
https://mclo.gs/40SS2pm
In Curseforge and Modrinth it is only possible to download version 0.15.5 by choosing manually, as apparently it is marked as only 1.19
Even at the moment I had the crash, the version already existed, I downloaded version 0.15.4 because filtering to only 1.19.2, version 0.15.5 does not appear

**Comment by Noaaan** [comment] 2022-10-01 18:56
That is slightly unrelated, since 0.15.5 will not work on 1.19+, and hence is marked so. 
![image](https://user-images.githubusercontent.com/4163353/193423944-975333f2-be8a-4c09-b0ed-c7c109109b5d.png)

Thanks for the log though

**Comment by Noaaan** [comment] 2022-11-28 20:18
https://pastebin.com/qtWQY8FU
New log to this

**Comment by Aquaeyes** [comment] 2022-12-27 04:58
[crash-2022-12-27_12.57.05-server copy.txt](https://github.com/Noaaan/MythicMetals/files/10305989/crash-2022-12-27_12.57.05-server.copy.txt)
Unsure if you need any more crash reports for it to help narrow it down?

**Comment by Noaaan** [comment] 2023-01-21 13:38
I am happy to announce this issue will be closed, as Fabric has merged a fix for it.

**Closed as completed by Noaaan** 2023-01-21 13:38 UTC
Labels: bug, compatibility, scheduled
