### ISSUE TITLE
Charm - Game crash when opening alloy forge

### ISSUE THREAD

**Issue by Boonthrall** [Noaaan/MythicMetals#135] opened 2022-12-06 18:54 UTC
I'm getting a "java.util.ConcurrentModificationException" when trying to open the forge interface.
This happens both on a server and singleplayer, with version 1.19.2, updating the owo-library didn't help.
Tested with both the Level 1 and Level 3 Forge.
Any idea what could be done to fix the error?
(Building a Level 2 Forge also doesn't work/is not an accepted structure, maybe i'm using the wrong blocks?)

[crash-2022-12-06_19.35.48-client.txt](https://github.com/Noaaan/MythicMetals/files/10169303/crash-2022-12-06_19.35.48-client.txt)

**Comment by Noaaan** [comment] 2022-12-06 19:16
This is a duplicate of the issue over at Alloy Forgery: https://github.com/wisp-forest/alloy-forgery/issues/80

This is caused by an incompatability with Charm. We have however made a mod that disables the modules of Charm that causes this crash, while we wait for them to make a proper fix. Feel free to follow the links in that issue to get it.

**Closed as completed by Noaaan** 2022-12-06 19:16 UTC
Labels: duplicate, compatibility, scheduled

**Comment by Boonthrall** [comment] 2022-12-06 19:34
Ah sorry, i missed that issue completely somehow!
Thank you for answering that fast

**Comment by Noaaan** [comment] 2022-12-07 12:32
Again, for anyone experiencing this issue, feel free to download Charm Fixer while we wait for an official fix.
CurseForge: https://www.curseforge.com/minecraft/mc-mods/charm-fixer
Modrinth: https://modrinth.com/mod/charm-fixer
